# backend/worker/redis_streams/streams_config.py

from backend.core.config import get_settings

settings = get_settings()

REDIS_URL = settings.REDIS_STREAMS_URL

REDIS_STREAM_RT = settings.REDIS_STREAM_RT
REDIS_STREAM_HIST = settings.REDIS_STREAM_HIST
REDIS_STREAM_DLQ = settings.REDIS_STREAM_DLQ

REDIS_GROUP_RT = settings.REDIS_GROUP_RT
REDIS_GROUP_HIST = settings.REDIS_GROUP_HIST

REDIS_DEDUP_KEY = settings.REDIS_DEDUP_KEY
REDIS_DEDUP_TTL = settings.REDIS_DEDUP_TTL

REDIS_STREAM_NUM_WORKERS = settings.REDIS_STREAM_NUM_WORKERS
REDIS_STREAM_BATCH_SIZE = settings.REDIS_STREAM_BATCH_SIZE
REDIS_STREAM_BLOCK_MS = settings.REDIS_STREAM_BLOCK_MS
REDIS_STREAM_CLAIM_IDLE_MS = settings.REDIS_STREAM_CLAIM_IDLE_MS
NUM_WORKERS = 15

# OFFLINE / REALTIME
HISTORY_LIMIT = 30
REALTIME_INTERVAL = 0.2